from django.urls import path
from .views import (
    ApiWorldviewDataView,
    ApiWorldviewDeepeningQuestionsView,
    ApiWorldviewDeepeningSubmitView,
    ApiWorldviewDeepeningApplyView,
    ApiWorldviewConsistencyView,
    ApiWorldviewConsistencyFixView,
    ApiWorldviewDeleteView,
    ApiFactionGenerateView,
    ApiLocationGenerateView,
    ApiRelationGenerateView,
    ApiWorldviewSettingView,
    ApiWorldviewFoundationView,
    ApiWorldviewPowerView,
    ApiWorldviewRacesView,
    ApiWorldviewSocietyView,
    ApiWorldviewCultureView,
    ApiWorldviewHistoryView,
    ApiWorldviewSpecialView,
    ApiWorldviewExportMarkdownView,
    ApiWorldviewChatHistoryView,
    ApiWorldviewChatHistoryDeleteView,
    ApiWorldviewChatStreamView
)

urlpatterns = [
    path('api/worldview/', ApiWorldviewDataView.as_view(), name='api_worldview_data'),
    path('api/worldview/<int:pk>/', ApiWorldviewDataView.as_view(), name='api_worldview_data_by_id'),
    path('api/worldview/<int:pk>/delete/', ApiWorldviewDeleteView.as_view(), name='api_worldview_delete'),
    path('api/worldview/<int:pk>/deepening/questions/', ApiWorldviewDeepeningQuestionsView.as_view(), name='api_worldview_deepening_questions'),
    path('api/worldview/<int:pk>/deepening/submit/', ApiWorldviewDeepeningSubmitView.as_view(), name='api_worldview_deepening_submit'),
    path('api/worldview/<int:pk>/deepening/apply/', ApiWorldviewDeepeningApplyView.as_view(), name='api_worldview_deepening_apply'),
    path('api/worldview/<int:pk>/consistency/check/', ApiWorldviewConsistencyView.as_view(), name='api_worldview_consistency'),
    path('api/worldview/<int:pk>/consistency/fix/', ApiWorldviewConsistencyFixView.as_view(), name='api_worldview_consistency_fix'),
    path('api/worldview/<int:pk>/factions/generate/', ApiFactionGenerateView.as_view(), name='api_faction_generate'),
    path('api/worldview/<int:pk>/locations/generate/', ApiLocationGenerateView.as_view(), name='api_location_generate'),
    path('api/worldview/<int:pk>/relations/generate/', ApiRelationGenerateView.as_view(), name='api_relation_generate'),
    path('api/worldview/<int:pk>/setting/', ApiWorldviewSettingView.as_view(), name='api_worldview_setting'),
    path('api/worldview/<int:pk>/foundation/', ApiWorldviewFoundationView.as_view(), name='api_worldview_foundation'),
    path('api/worldview/<int:pk>/power/', ApiWorldviewPowerView.as_view(), name='api_worldview_power'),
    path('api/worldview/<int:pk>/races/', ApiWorldviewRacesView.as_view(), name='api_worldview_races'),
    path('api/worldview/<int:pk>/society/', ApiWorldviewSocietyView.as_view(), name='api_worldview_society'),
    path('api/worldview/<int:pk>/culture/', ApiWorldviewCultureView.as_view(), name='api_worldview_culture'),
    path('api/worldview/<int:pk>/history/', ApiWorldviewHistoryView.as_view(), name='api_worldview_history'),
    path('api/worldview/<int:pk>/special/', ApiWorldviewSpecialView.as_view(), name='api_worldview_special'),
    path('api/worldview/<int:pk>/export/markdown/', ApiWorldviewExportMarkdownView.as_view(), name='api_worldview_export_markdown'),
    path('api/worldview/<int:pk>/chat/history/', ApiWorldviewChatHistoryView.as_view(), name='api_worldview_chat_history'),
    path('api/worldview/<int:pk>/chat/history/delete/', ApiWorldviewChatHistoryDeleteView.as_view(), name='api_worldview_chat_history_delete'),
    path('api/worldview/<int:pk>/chat/stream/', ApiWorldviewChatStreamView.as_view(), name='api_worldview_chat_stream'),
]
