# Generated by Django 5.2.13 on 2026-09-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_alter_graphedge_edge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphnode',
            name='node_type',
            field=models.CharField(choices=[('character', '角色'), ('faction', '势力/阵营'), ('location', '地点'), ('event', '事件')], max_length=20, verbose_name='节点类型'),
        ),
    ]
