# Generated by Django 5.2.13 on 2026-09-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_alter_graphnode_node_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphedge',
            name='edge_type',
            field=models.CharField(choices=[('朋友', '朋友'), ('恋人', '恋人'), ('配偶', '配偶'), ('父母', '父母'), ('子女', '子女'), ('兄弟姐妹', '兄弟姐妹'), ('师父', '师父'), ('徒弟', '徒弟'), ('敌人', '敌人'), ('对手', '对手'), ('导师', '导师'), ('门生', '门生'), ('盟友', '盟友'), ('亲属', '亲属'), ('君主', '君主'), ('臣子', '臣子'), ('其他', '其他'), ('belongs_to', '隶属于'), ('occurs_at', '发生于'), ('involves', '涉及'), ('located_in', '位于'), ('present_at', '在场'), ('trajectory', '轨迹')], max_length=30, verbose_name='关系类型'),
        ),
    ]
