# Generated by Django 5.2.13 on 2026-05-11 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outline', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='是否定稿')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否为当前版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('outline_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_versions', to='outline.outlineversion', verbose_name='关联大纲版本')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_versions', to='project.projectlist', verbose_name='项目')),
            ],
            options={
                'verbose_name': '卷版本',
                'verbose_name_plural': '卷版本',
                'db_table': 'volume_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='VolumeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.IntegerField(verbose_name='卷号')),
                ('title', models.CharField(max_length=255, verbose_name='卷标题')),
                ('summary', models.TextField(blank=True, verbose_name='卷摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('volume_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='volume.volumeversion', verbose_name='卷版本')),
            ],
            options={
                'verbose_name': '卷',
                'verbose_name_plural': '卷',
                'db_table': 'volume_list',
                'ordering': ['volume_number'],
                'unique_together': {('volume_version', 'volume_number')},
            },
        ),
    ]
