# Generated by Django 5.2.13 on 2026-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0002_volumelist_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumelist',
            name='chapters',
            field=models.JSONField(blank=True, default=list, verbose_name='章节列表'),
        ),
    ]
