# Generated by Django 5.2.13 on 2026-09-11 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0006_remove_outline_is_current_remove_outline_snapshot'),
        ('volume', '0002_remove_old_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='outline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volumes', to='outline.outline', verbose_name='关联大纲'),
        ),
    ]
