# Generated by Django 5.2.13 on 2026-06-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0003_volumelist_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumelist',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='卷大纲'),
        ),
    ]
