# Generated by Django 5.2.13 on 2026-06-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0004_volumelist_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
