# Generated by Django 5.2.13 on 2026-06-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0005_volumelist_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumelist',
            name='chapter_count',
            field=models.IntegerField(default=0, verbose_name='预估章节数'),
        ),
    ]
