# Generated by Django 4.2.30 on 2026-07-11 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('azure', 'Azure OpenAI'), ('claude', 'Claude'), ('deepseek', 'DeepSeek'), ('bigmodel', 'BigModel'), ('qwen', '通义千问'), ('ollama', 'Ollama'), ('custom', '自定义')], default='openai', max_length=100, verbose_name='提供商')),
                ('model_name', models.CharField(max_length=200, verbose_name='模型名称')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API密钥')),
                ('base_url', models.URLField(blank=True, verbose_name='API地址')),
                ('max_tokens', models.IntegerField(default=2000, verbose_name='最大Token数')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度参数')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('test_passed', models.BooleanField(default=False, verbose_name='测试是否通过')),
                ('input_price', models.FloatField(default=0, verbose_name='输入单价(元/百万Token)')),
                ('output_price', models.FloatField(default=0, verbose_name='输出单价(元/百万Token)')),
                ('cache_hit_price', models.FloatField(default=0, verbose_name='缓存命中单价(元/百万Token)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'LLM配置',
                'verbose_name_plural': 'LLM配置',
                'db_table': 'llm_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('default', '默认'), ('worldview_build', '世界观构建'), ('worldview_deepen', '世界观深化'), ('worldview_consistency', '世界观一致性检查'), ('character_design', '角色设计'), ('character_polish', '角色润色'), ('character_check', '角色校验'), ('timeline_generate', '时间线生成'), ('timeline_merge', '时间线合并'), ('timeline_check', '时间线检查'), ('outline_optimize', '大纲优化'), ('volume_batch_generate', '卷批量生成'), ('volume_single_generate', '单卷生成'), ('volume_single_optimize', '单卷优化'), ('volume_chat', '卷对话写作'), ('chapter_batch_generate', '章节批量生成'), ('chapter_split', '章节拆分'), ('chapter_optimize', '章节优化'), ('chapter_verify', '章节校验'), ('note_polish', '随手记润色')], default='default', max_length=50, verbose_name='任务类型')),
                ('max_tokens', models.IntegerField(blank=True, null=True, verbose_name='最大Token数(空=继承场景默认)')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='温度参数(空=继承场景默认)')),
                ('llm_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_configs', to='user.llmconfig', verbose_name='LLM配置')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_llm_configs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户LLM配置',
                'verbose_name_plural': '用户LLM配置',
                'db_table': 'user_llm_config',
                'unique_together': {('user', 'task_type')},
            },
        ),
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='模型名称')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='输入Token数')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='输出Token数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token数')),
                ('input_cache_hit_tokens', models.IntegerField(default=0, verbose_name='输入缓存命中Token数')),
                ('input_cache_miss_tokens', models.IntegerField(default=0, verbose_name='输入缓存未命中Token数')),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='费用')),
                ('task_type', models.CharField(blank=True, max_length=50, verbose_name='任务类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('llm_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage_logs', to='user.llmconfig', verbose_name='LLM配置')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_usage_logs', to='project.projectlist', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Token使用日志',
                'verbose_name_plural': 'Token使用日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='user_tokenu_created_db49d5_idx'), models.Index(fields=['user', 'created_at'], name='user_tokenu_user_id_3745d7_idx')],
            },
        ),
    ]
