# Generated by Django 5.2.13 on 2026-06-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusagelog',
            name='prompt_cache_hit_tokens',
            field=models.IntegerField(default=0, verbose_name='输入缓存命中Token数'),
        ),
        migrations.AddField(
            model_name='tokenusagelog',
            name='prompt_cache_miss_tokens',
            field=models.IntegerField(default=0, verbose_name='输入缓存未命中Token数'),
        ),
    ]
