# Generated by Django 5.2.13 on 2026-06-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tokenusagelog_prompt_cache_hit_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenusagelog',
            name='cache_hit',
        ),
        migrations.RemoveField(
            model_name='tokenusagelog',
            name='completion_tokens',
        ),
        migrations.RemoveField(
            model_name='tokenusagelog',
            name='prompt_cache_hit_tokens',
        ),
        migrations.RemoveField(
            model_name='tokenusagelog',
            name='prompt_cache_miss_tokens',
        ),
        migrations.RemoveField(
            model_name='tokenusagelog',
            name='prompt_tokens',
        ),
        migrations.AddField(
            model_name='tokenusagelog',
            name='input_cache_hit_tokens',
            field=models.IntegerField(default=None, null=True, verbose_name='输入缓存命中Token数'),
        ),
        migrations.AddField(
            model_name='tokenusagelog',
            name='input_cache_miss_tokens',
            field=models.IntegerField(default=None, null=True, verbose_name='输入缓存未命中Token数'),
        ),
        migrations.AddField(
            model_name='tokenusagelog',
            name='input_tokens',
            field=models.IntegerField(default=0, verbose_name='输入Token数'),
        ),
        migrations.AddField(
            model_name='tokenusagelog',
            name='output_tokens',
            field=models.IntegerField(default=0, verbose_name='输出Token数'),
        ),
    ]
