# Generated by Django 5.2.13 on 2026-09-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userembeddingconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('azure', 'Azure OpenAI'), ('claude', 'Claude'), ('deepseek', 'DeepSeek'), ('bigmodel', 'BigModel'), ('qwen', '通义千问'), ('gemini', 'Gemini'), ('xiaomi', '小米MiMo'), ('ollama', 'Ollama'), ('custom', '自定义')], default='openai', max_length=100, verbose_name='提供商'),
        ),
    ]
