# Generated by Django 5.2.13 on 2026-06-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_tokenusagelog_cache_hit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenusagelog',
            name='input_cache_hit_tokens',
            field=models.IntegerField(default=0, verbose_name='输入缓存命中Token数'),
        ),
        migrations.AlterField(
            model_name='tokenusagelog',
            name='input_cache_miss_tokens',
            field=models.IntegerField(default=0, verbose_name='输入缓存未命中Token数'),
        ),
    ]
