# Generated by Django 5.2.13 on 2026-06-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_tokenusagelog_input_cache_hit_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='cache_hit_price',
            field=models.FloatField(default=0, verbose_name='缓存命中单价(元/百万Token)'),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='input_price',
            field=models.FloatField(default=0, verbose_name='输入单价(元/百万Token)'),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='output_price',
            field=models.FloatField(default=0, verbose_name='输出单价(元/百万Token)'),
        ),
    ]
