# Generated by Django 5.2.13 on 2026-06-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_llmconfig_cache_hit_price_llmconfig_input_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userllmconfig',
            name='task_type',
            field=models.CharField(choices=[('default', '默认'), ('worldview_build', '构建世界观'), ('worldview_deepen', '世界观深化'), ('worldview_consistency', '一致性检查'), ('character_design', '角色设计'), ('location_design', '地点设计'), ('faction_design', '阵营设计'), ('outline_optimize', '大纲优化'), ('volume_generate', '卷生成'), ('volume_optimize', '卷优化'), ('volume_chat', '卷对话'), ('chapter_generate', '章节生成'), ('content_generate', '内容生成'), ('timeline_generate', '时间线生成'), ('dialogue_generate', '对话生成')], default='default', max_length=50, verbose_name='任务类型'),
        ),
    ]
