# Generated by Django 5.2.13 on 2026-06-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userllmconfig_max_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='test_passed',
            field=models.BooleanField(default=False, verbose_name='测试是否通过'),
        ),
    ]
