# Generated by Django 5.2.13 on 2026-05-05 13:31

import apps.core.models
import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1, verbose_name='版本号')),
                ('content', models.TextField(verbose_name='大纲内容')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='是否定稿')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('snapshot', models.TextField(blank=True, verbose_name='内容快照')),
            ],
            options={
                'verbose_name': '大纲版本',
                'verbose_name_plural': '大纲版本',
                'db_table': 'outline_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=apps.core.models.generate_project_title, max_length=255, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('finalized', models.BooleanField(default=False, verbose_name='是否定稿')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.IntegerField(verbose_name='卷号')),
                ('title', models.CharField(max_length=255, verbose_name='卷标题')),
                ('summary', models.TextField(blank=True, verbose_name='卷摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '卷',
                'verbose_name_plural': '卷',
                'db_table': 'volume',
                'ordering': ['volume_number'],
            },
        ),
        migrations.CreateModel(
            name='OutlineMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('outline_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.outlineversion', verbose_name='大纲版本')),
            ],
            options={
                'verbose_name': '大纲消息',
                'verbose_name_plural': '大纲消息',
                'db_table': 'outline_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='outlineversion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outline_versions', to='core.project', verbose_name='项目'),
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=64, unique=True)),
                ('messages', models.JSONField(default=list, verbose_name='聊天消息')),
                ('current_outline', models.TextField(blank=True, verbose_name='当前大纲')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to='core.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '聊天历史',
                'verbose_name_plural': '聊天历史',
                'db_table': 'chat_history',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChapterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='是否定稿')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_versions', to='core.volume', verbose_name='卷')),
            ],
            options={
                'verbose_name': '章节版本',
                'verbose_name_plural': '章节版本',
                'db_table': 'chapter_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='VolumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='是否定稿')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('outline_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_versions', to='core.outlineversion', verbose_name='关联大纲版本')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_versions', to='core.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '卷版本',
                'verbose_name_plural': '卷版本',
                'db_table': 'volume_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='volume',
            name='volume_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='core.volumeversion', verbose_name='卷版本'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(verbose_name='章节号')),
                ('title', models.CharField(max_length=255, verbose_name='章节标题')),
                ('summary', models.TextField(blank=True, verbose_name='章节摘要')),
                ('content', models.TextField(blank=True, verbose_name='章节内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.chapterversion', verbose_name='章节版本')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'db_table': 'chapter',
                'ordering': ['chapter_number'],
                'unique_together': {('chapter_version', 'chapter_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('volume_version', 'volume_number')},
        ),
    ]
