# Generated by Django 5.2.13 on 2026-05-05 22:30

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterversion',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='outlineversion',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='volumeversion',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='session_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('qwen', 'Qwen'), ('gemini', 'Gemini'), ('custom', '自定义')], max_length=50, verbose_name='LLM提供商')),
                ('api_key', models.TextField(verbose_name='API密钥')),
                ('base_url', models.URLField(blank=True, verbose_name='API地址')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度')),
                ('max_tokens', models.IntegerField(default=4096, verbose_name='最大token数')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认配置')),
                ('task_type', models.CharField(choices=[('outline', '大纲生成'), ('volume', '卷结构生成'), ('chapter', '章节概要生成'), ('content', '章节内容生成'), ('other', '其他任务')], default='other', max_length=50, verbose_name='适用任务类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'LLM配置',
                'verbose_name_plural': 'LLM配置',
                'db_table': 'llm_config',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('outline', '大纲生成'), ('volume', '卷结构生成'), ('chapter', '章节概要生成'), ('content', '章节内容生成')], max_length=50, verbose_name='任务类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('llm_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_usages', to='core.llmconfig', verbose_name='LLM配置')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_llm_configs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户任务LLM配置',
                'verbose_name_plural': '用户任务LLM配置',
                'db_table': 'user_llm_config',
                'unique_together': {('user', 'task_type')},
            },
        ),
    ]
