# Generated by Django 5.2.13 on 2026-05-05 23:14

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chapterversion_is_deleted_outlineversion_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userllmconfig',
            name='max_tokens',
            field=models.IntegerField(blank=True, null=True, verbose_name='最大token数'),
        ),
        migrations.AddField(
            model_name='userllmconfig',
            name='temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='温度'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='session_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('outline', '大纲生成'), ('volume', '卷结构生成'), ('chapter', '章节概要生成'), ('content', '章节内容生成'), ('other', '其他任务')], max_length=50, verbose_name='任务类型')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='输入token数')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='输出token数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总token数')),
                ('cache_hit', models.BooleanField(default=False, verbose_name='是否命中缓存')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('llm_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='core.llmconfig', verbose_name='LLM配置')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_usage_logs', to='core.project', verbose_name='项目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Token使用日志',
                'verbose_name_plural': 'Token使用日志',
                'db_table': 'token_usage_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
