# Generated by Django 5.2.13 on 2026-05-06 06:48

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userllmconfig_max_tokens_userllmconfig_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='session_id',
            field=models.CharField(default=apps.core.models.generate_session_id, max_length=64, unique=True),
        ),
    ]
