# Generated by Django 5.2.13 on 2026-05-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_project_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='word_count',
            field=models.IntegerField(default=0, verbose_name='字数'),
        ),
    ]
