# Generated by Django 4.2.30 on 2026-07-11 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名/名称')),
                ('role_type', models.CharField(default='配角', max_length=20, verbose_name='角色类型')),
                ('gender', models.CharField(default='未知', max_length=10, verbose_name='性别')),
                ('appearance', models.TextField(blank=True, verbose_name='外貌特征')),
                ('personality', models.TextField(blank=True, verbose_name='性格特点')),
                ('backstory', models.TextField(blank=True, verbose_name='背景故事')),
                ('motivation', models.TextField(blank=True, verbose_name='核心动机')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='人物标签/签名')),
                ('faction', models.CharField(blank=True, max_length=255, verbose_name='势力/阵营')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('identity', models.CharField(blank=True, default='', max_length=255, verbose_name='身份/称号')),
                ('relationships', models.JSONField(blank=True, default=list, verbose_name='人际关系')),
                ('experiences', models.JSONField(blank=True, default=list, verbose_name='经历')),
                ('development', models.TextField(blank=True, default='', verbose_name='成长轨迹')),
                ('strengths', models.TextField(blank=True, default='', verbose_name='优点/特长')),
                ('flaws', models.TextField(blank=True, default='', verbose_name='缺点')),
                ('obsession', models.TextField(blank=True, default='', verbose_name='执念/软肋')),
                ('taboos', models.TextField(blank=True, default='', verbose_name='禁忌')),
                ('abilities', models.TextField(blank=True, default='', verbose_name='能力')),
                ('secrets', models.TextField(blank=True, default='', verbose_name='秘密')),
                ('dark_history', models.TextField(blank=True, default='', verbose_name='过往黑历史')),
                ('weaknesses', models.TextField(blank=True, default='', verbose_name='弱点/代价')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='project.projectlist', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '人物',
                'verbose_name_plural': '人物',
                'db_table': 'character',
                'ordering': ['role_type', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_character_name_per_project'),
        ),
    ]
