# Generated by Django 5.2.13 on 2026-05-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
