# Generated by Django 5.2.13 on 2026-07-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dynamic_states',
            field=models.JSONField(blank=True, default=dict, verbose_name='动态状态'),
        ),
    ]
