# Generated by Django 5.2.13 on 2026-09-09 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
        ('characters', '0002_add_dynamic_states'),
        ('project', '0003_projectlist_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='source',
            field=models.CharField(blank=True, choices=[('manual', '手动创建'), ('ai_generate', 'AI生成'), ('outline_extract', '大纲提取'), ('volume_extract', '卷提取'), ('chapter_discover', '章节发现')], default='manual', max_length=20, verbose_name='创建来源'),
        ),
        migrations.CreateModel(
            name='CharacterTrajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('chapter', '章节生成'), ('manual', '手动记录'), ('outline_extract', '大纲提取'), ('volume_extract', '卷提取')], default='chapter', max_length=20, verbose_name='记录来源')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='当前所在地')),
                ('status', models.CharField(blank=True, default='', max_length=100, verbose_name='当前状态（在世/失踪/死亡等）')),
                ('power_level', models.CharField(blank=True, default='', max_length=100, verbose_name='实力/等级')),
                ('faction', models.CharField(blank=True, default='', max_length=255, verbose_name='所属势力')),
                ('identity', models.CharField(blank=True, default='', max_length=255, verbose_name='身份/称号')),
                ('emotional_state', models.CharField(blank=True, default='', max_length=255, verbose_name='情绪/心理状态')),
                ('physical_state', models.CharField(blank=True, default='', max_length=255, verbose_name='身体/健康状态')),
                ('relationship_changes', models.JSONField(blank=True, default=dict, verbose_name='关系变化')),
                ('ability_progress', models.TextField(blank=True, default='', verbose_name='能力/技能进展')),
                ('key_events', models.JSONField(blank=True, default=list, verbose_name='重大事件')),
                ('summary', models.TextField(blank=True, default='', verbose_name='轨迹摘要')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始提取数据')),
                ('story_year', models.IntegerField(blank=True, null=True, verbose_name='故事年份')),
                ('story_month', models.IntegerField(blank=True, null=True, verbose_name='故事月份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chapter.chapterlist', verbose_name='关联章节')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajectories', to='characters.character', verbose_name='角色')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_trajectories', to='project.projectlist', verbose_name='项目')),
            ],
            options={
                'verbose_name': '角色轨迹',
                'verbose_name_plural': '角色轨迹',
                'db_table': 'character_trajectory',
                'ordering': ['character', 'chapter__chapter_number', 'created_at'],
                'indexes': [models.Index(fields=['character', 'created_at'], name='character_t_charact_dae53c_idx'), models.Index(fields=['project', 'created_at'], name='character_t_project_b3f584_idx'), models.Index(fields=['chapter'], name='character_t_chapter_e8265e_idx')],
            },
        ),
    ]
