# Generated by Django 5.2.13 on 2026-09-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_source_charactertrajectory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='character',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='character',
            name='backstory',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dark_history',
        ),
        migrations.RemoveField(
            model_name='character',
            name='development',
        ),
        migrations.RemoveField(
            model_name='character',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='character',
            name='flaws',
        ),
        migrations.RemoveField(
            model_name='character',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='character',
            name='obsession',
        ),
        migrations.RemoveField(
            model_name='character',
            name='personality',
        ),
        migrations.RemoveField(
            model_name='character',
            name='secrets',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='character',
            name='taboos',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weaknesses',
        ),
        migrations.AddField(
            model_name='character',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='角色内容（Markdown）'),
        ),
    ]
