# Generated by Django 5.2.13 on 2026-06-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='abilities',
            field=models.TextField(blank=True, default='', verbose_name='能力'),
        ),
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='character',
            name='dark_history',
            field=models.TextField(blank=True, default='', verbose_name='过往黑历史'),
        ),
        migrations.AddField(
            model_name='character',
            name='development',
            field=models.TextField(blank=True, default='', verbose_name='成长轨迹'),
        ),
        migrations.AddField(
            model_name='character',
            name='experiences',
            field=models.JSONField(blank=True, default=list, verbose_name='经历'),
        ),
        migrations.AddField(
            model_name='character',
            name='flaws',
            field=models.TextField(blank=True, default='', verbose_name='缺点'),
        ),
        migrations.AddField(
            model_name='character',
            name='identity',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='身份/称号'),
        ),
        migrations.AddField(
            model_name='character',
            name='obsession',
            field=models.TextField(blank=True, default='', verbose_name='执念/软肋'),
        ),
        migrations.AddField(
            model_name='character',
            name='relationships',
            field=models.JSONField(blank=True, default=list, verbose_name='人际关系'),
        ),
        migrations.AddField(
            model_name='character',
            name='secrets',
            field=models.TextField(blank=True, default='', verbose_name='秘密'),
        ),
        migrations.AddField(
            model_name='character',
            name='strengths',
            field=models.TextField(blank=True, default='', verbose_name='优点/特长'),
        ),
        migrations.AddField(
            model_name='character',
            name='taboos',
            field=models.TextField(blank=True, default='', verbose_name='禁忌'),
        ),
        migrations.AddField(
            model_name='character',
            name='weaknesses',
            field=models.TextField(blank=True, default='', verbose_name='弱点/代价'),
        ),
    ]
