# Generated by Django 5.2.13 on 2026-09-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_remove_character_abilities_and_more'),
        ('project', '0003_projectlist_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactertrajectory',
            options={'ordering': ['character', 'order', 'created_at'], 'verbose_name': '角色轨迹', 'verbose_name_plural': '角色轨迹'},
        ),
        migrations.RemoveIndex(
            model_name='charactertrajectory',
            name='character_t_charact_dae53c_idx',
        ),
        migrations.RemoveIndex(
            model_name='charactertrajectory',
            name='character_t_chapter_e8265e_idx',
        ),
        migrations.RemoveField(
            model_name='charactertrajectory',
            name='ability_progress',
        ),
        migrations.RemoveField(
            model_name='charactertrajectory',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='charactertrajectory',
            name='emotional_state',
        ),
        migrations.RemoveField(
            model_name='charactertrajectory',
            name='faction',
        ),
        migrations.RemoveField(
            model_name='charactertrajectory',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='charactertrajectory',
            name='key_events',
        ),
        migrations.RemoveField(
            model_name='charactertrajectory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='charactertrajectory',
            name='physical_state',
        ),
        migrations.RemoveField(
            model_name='charactertrajectory',
            name='power_level',
        ),
        migrations.RemoveField(
            model_name='charactertrajectory',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='charactertrajectory',
            name='relationship_changes',
        ),
        migrations.RemoveField(
            model_name='charactertrajectory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='charactertrajectory',
            name='story_month',
        ),
        migrations.RemoveField(
            model_name='charactertrajectory',
            name='story_year',
        ),
        migrations.RemoveField(
            model_name='charactertrajectory',
            name='summary',
        ),
        migrations.AddField(
            model_name='charactertrajectory',
            name='chapter_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='涉及章节ID列表'),
        ),
        migrations.AddField(
            model_name='charactertrajectory',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='轨迹详情'),
        ),
        migrations.AddField(
            model_name='charactertrajectory',
            name='end_time',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='结束时间（故事内）'),
        ),
        migrations.AddField(
            model_name='charactertrajectory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序序号'),
        ),
        migrations.AddField(
            model_name='charactertrajectory',
            name='start_time',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='起始时间（故事内）'),
        ),
        migrations.AddField(
            model_name='charactertrajectory',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='轨迹标题'),
        ),
        migrations.AddField(
            model_name='charactertrajectory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='charactertrajectory',
            name='source',
            field=models.CharField(choices=[('chapter', '章节生成'), ('manual', '手动记录'), ('outline_extract', '大纲提取'), ('volume_extract', '卷提取')], default='manual', max_length=20, verbose_name='记录来源'),
        ),
        migrations.AddIndex(
            model_name='charactertrajectory',
            index=models.Index(fields=['character', 'order'], name='character_t_charact_7482ed_idx'),
        ),
    ]
