# Generated by Django 5.2.13 on 2026-06-04 13:49

from django.db import migrations
from loguru import logger


def clean_age_forward(apps, schema_editor):
    """去除 age 中的 '岁' 后缀并转为整数"""
    Character = apps.get_model('characters', 'Character')
    chars = Character.objects.filter(is_deleted=False).exclude(age='')
    updated = 0
    for c in chars:
        raw = c.age or ''
        if not raw:
            continue
        cleaned = raw.replace('岁', '').strip()
        try:
            val = int(cleaned)
            if str(val) != raw:
                c.age = str(val)
                c.save(update_fields=['age'])
                updated += 1
                logger.info(f"  {c.name}(id={c.id}): '{raw}' → '{val}'")
        except (ValueError, TypeError):
            logger.warning(f"  {c.name}(id={c.id}): 无法解析 age='{raw}'，跳过")
    logger.info(f"清洗完成: 更新 {updated} 个角色")


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_add_character_new_fields'),
    ]

    operations = [
        migrations.RunPython(clean_age_forward, migrations.RunPython.noop),
    ]
