# Generated by Django 5.2.13 on 2026-06-04 15:09

from django.db import migrations, models
from loguru import logger


ROLE_TYPE_MAP = {
    'protagonist': '主角',
    'supporting': '配角',
    'antagonist': '反派',
    'minor': '路人',
    'narrator': '旁白/叙述者',
}

GENDER_MAP = {
    'male': '男',
    'female': '女',
    'unknown': '未知',
}


def convert_role_gender_to_chinese(apps, schema_editor):
    Character = apps.get_model('characters', 'Character')
    updated_role = 0
    updated_gender = 0
    for c in Character.objects.all():
        changed = False
        if c.role_type in ROLE_TYPE_MAP:
            c.role_type = ROLE_TYPE_MAP[c.role_type]
            changed = True
            updated_role += 1
        if c.gender in GENDER_MAP:
            c.gender = GENDER_MAP[c.gender]
            changed = True
            updated_gender += 1
        if changed:
            c.save(update_fields=['role_type', 'gender'])
    logger.info(f"转换角色类型 {updated_role} 个, 性别 {updated_gender} 个")


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_change_age_to_positive_integer'),
    ]

    operations = [
        migrations.RunPython(convert_role_gender_to_chinese, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(default='未知', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='character',
            name='role_type',
            field=models.CharField(default='配角', max_length=20, verbose_name='角色类型'),
        ),
    ]
