# Generated by Django 5.2.13 on 2026-06-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_migrate_relationships_to_chinese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='extra',
        ),
    ]
