# Generated by Django 4.2.30 on 2026-07-11 15:02

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeVector',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='向量记录ID')),
                ('doc_type', models.CharField(choices=[('outline', '大纲版本'), ('worldview', '世界观分区'), ('character', '角色'), ('volume', '卷大纲'), ('chapter', '章节段落')], db_index=True, max_length=20, verbose_name='文档类型')),
                ('content', models.TextField(verbose_name='原始文本内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展元数据(JSONB)')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, verbose_name='embedding向量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_vectors', to='project.projectlist', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '知识库向量记录',
                'verbose_name_plural': '知识库向量记录',
                'db_table': 'knowledge_vector',
                'indexes': [models.Index(fields=['project_id', 'doc_type'], name='idx_kv_project_doc'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_kv_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
