# Generated by Django 5.2.13 on 2026-05-11 06:19

import apps.project.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100, verbose_name='提供商')),
                ('model_name', models.CharField(max_length=200, verbose_name='模型名称')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API密钥')),
                ('api_base', models.URLField(blank=True, verbose_name='API地址')),
                ('max_tokens', models.IntegerField(default=2000, verbose_name='最大Token数')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'LLM配置',
                'verbose_name_plural': 'LLM配置',
                'db_table': 'llm_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=apps.project.models.generate_project_title, max_length=255, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('status', models.CharField(default='draft', max_length=50, verbose_name='状态')),
                ('finalized', models.BooleanField(default=False, verbose_name='是否定稿')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_lists', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'project_list',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_tokens', models.IntegerField(default=2000, verbose_name='最大Token数')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度参数')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('llm_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_configs', to='project.llmconfig', verbose_name='LLM配置')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_llm_configs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户LLM配置',
                'verbose_name_plural': '用户LLM配置',
                'db_table': 'user_llm_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='模型名称')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='提示Token数')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='完成Token数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token数')),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='费用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('llm_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage_logs', to='project.llmconfig', verbose_name='LLM配置')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_usage_logs', to='project.projectlist', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Token使用日志',
                'verbose_name_plural': 'Token使用日志',
                'db_table': 'token_usage_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='token_usage_created_a4ead7_idx'), models.Index(fields=['user', 'created_at'], name='token_usage_user_id_7959a8_idx')],
            },
        ),
    ]
