# Generated by Django 4.2.30 on 2026-07-11 15:02

import apps.project.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=apps.project.models.generate_project_title, max_length=255, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('status', models.CharField(default='draft', max_length=50, verbose_name='状态')),
                ('finalized', models.BooleanField(default=False, verbose_name='是否定稿')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_lists', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'project_list',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectlist',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_project_title_per_user'),
        ),
    ]
