# Generated by Django 5.2.13 on 2026-07-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='min_words_per_chapter',
            field=models.PositiveIntegerField(default=3000, verbose_name='单章最少字数'),
        ),
    ]
