# Generated by Django 4.2.30 on 2026-05-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worldview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('worldview', '世界观'), ('setting', '设定体系'), ('history', '历史背景'), ('culture', '文化风俗'), ('location', '地点场景'), ('rule', '规则设定'), ('plot_foreshadow', '情节伏笔'), ('other', '其他')], default='worldview', max_length=50, verbose_name='分类')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='关键词')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='详细内容')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldviews', to='project.projectlist', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '世界观',
                'verbose_name_plural': '世界观',
                'db_table': 'worldview',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名/名称')),
                ('role_type', models.CharField(choices=[('protagonist', '主角'), ('supporting', '配角'), ('antagonist', '反派'), ('minor', '路人'), ('narrator', '旁白/叙述者')], default='supporting', max_length=20, verbose_name='角色类型')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别')),
                ('appearance', models.TextField(blank=True, verbose_name='外貌特征')),
                ('personality', models.TextField(blank=True, verbose_name='性格特点')),
                ('backstory', models.TextField(blank=True, verbose_name='背景故事')),
                ('motivation', models.TextField(blank=True, verbose_name='核心动机')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='人物标签/签名')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='project.projectlist', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '人物',
                'verbose_name_plural': '人物',
                'db_table': 'character',
                'ordering': ['role_type', 'name'],
            },
        ),
    ]
