# Generated by Django 5.2.13 on 2026-05-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_add_worldview_and_character'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='character',
            table=None,
        ),
    ]
