# Generated by Django 5.2.13 on 2026-05-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_character_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='worldview',
            table=None,
        ),
    ]
