# Generated by Django 5.2.13 on 2026-05-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_worldview_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userllmconfig',
            name='llm_config',
        ),
        migrations.RemoveField(
            model_name='tokenusagelog',
            name='llm_config',
        ),
        migrations.RemoveField(
            model_name='tokenusagelog',
            name='project',
        ),
        migrations.RemoveField(
            model_name='tokenusagelog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userllmconfig',
            name='user',
        ),
        migrations.AlterModelTable(
            name='character',
            table='character',
        ),
        migrations.AlterModelTable(
            name='worldview',
            table='worldview',
        ),
        migrations.DeleteModel(
            name='LLMConfig',
        ),
        migrations.DeleteModel(
            name='TokenUsageLog',
        ),
        migrations.DeleteModel(
            name='UserLLMConfig',
        ),
    ]
