# Generated by Django 4.2.30 on 2026-05-13 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_userllmconfig_llm_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldviewVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1, verbose_name='版本号')),
                ('content', models.TextField(verbose_name='世界观内容')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldview_versions', to='project.projectlist', verbose_name='项目')),
            ],
            options={
                'verbose_name': '世界观版本',
                'verbose_name_plural': '世界观版本',
                'db_table': 'worldview_version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorldviewChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('worldview_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to='project.worldviewversion', verbose_name='世界观版本')),
            ],
            options={
                'verbose_name': '世界观聊天历史',
                'verbose_name_plural': '世界观聊天历史',
                'db_table': 'worldview_chat_history',
                'ordering': ['created_at'],
            },
        ),
    ]
