# Generated by Django 5.2.13 on 2026-05-13 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_worldviewversion_worldviewchathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldviewchathistory',
            name='worldview_version',
        ),
        migrations.AddField(
            model_name='worldviewchathistory',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worldview_chat_histories', to='project.projectlist', verbose_name='项目'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WorldviewVersion',
        ),
    ]
