# Generated by Django 5.2.13 on 2026-05-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_worldviewchathistory_worldview_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worldview',
            options={'verbose_name': '世界观', 'verbose_name_plural': '世界观'},
        ),
        migrations.RemoveField(
            model_name='worldview',
            name='category',
        ),
        migrations.RemoveField(
            model_name='worldview',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='worldview',
            name='title',
        ),
    ]
