# Generated by Django 4.2.30 on 2026-05-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_worldview_options_remove_worldview_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.CharField(blank=True, max_length=255, verbose_name='势力/阵营'),
        ),
    ]
