# Generated by Django 4.2.30 on 2026-05-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_character_faction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_character_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='projectlist',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_project_title_per_user'),
        ),
    ]
