# Generated by Django 5.2.13 on 2026-05-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldviewchathistory',
            name='project',
        ),
        migrations.DeleteModel(
            name='Worldview',
        ),
        migrations.DeleteModel(
            name='WorldviewChatHistory',
        ),
    ]
