# Generated by Django 4.2.30 on 2026-05-17 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0008_alter_worldview_options_remove_worldview_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='随手记内容')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('published', '已发布')], default='unused', max_length=20, verbose_name='状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='project.projectlist', verbose_name='项目')),
            ],
            options={
                'verbose_name': '随手记',
                'verbose_name_plural': '随手记',
                'db_table': 'note',
                'ordering': ['-created_at'],
            },
        ),
    ]
