# Generated by Django 5.2.13 on 2026-05-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='project_note',
        ),
    ]
