# Generated by Django 4.2.30 on 2026-07-11 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1, verbose_name='版本号')),
                ('content', models.TextField(verbose_name='大纲内容')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='是否定稿')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否为当前版本')),
                ('snapshot', models.TextField(blank=True, verbose_name='内容快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outline_versions', to='project.projectlist', verbose_name='项目')),
            ],
            options={
                'verbose_name': '大纲版本',
                'verbose_name_plural': '大纲版本',
                'db_table': 'outline_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='OutlineExpansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('world', '世界观'), ('magic', '设定体系'), ('history', '历史背景'), ('culture', '文化风俗'), ('location', '地点场景'), ('rule', '规则设定'), ('plot', '情节伏笔'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('key_name', models.CharField(max_length=200, verbose_name='关键词')),
                ('content', models.TextField(verbose_name='扩展内容')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('outline_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expansions', to='outline.outlineversion', verbose_name='大纲版本')),
            ],
            options={
                'verbose_name': '大纲扩展',
                'verbose_name_plural': '大纲扩展',
                'db_table': 'outline_expansion',
                'ordering': ['category', 'key_name'],
            },
        ),
        migrations.CreateModel(
            name='OutlineChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('outline_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outline_chat_histories', to='outline.outlineversion', verbose_name='大纲版本')),
            ],
            options={
                'verbose_name': '大纲聊天历史',
                'verbose_name_plural': '大纲聊天历史',
                'db_table': 'outline_chat_history',
                'ordering': ['created_at'],
            },
        ),
    ]
