# Generated by Django 5.2.13 on 2026-09-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlineversion',
            name='last_options',
            field=models.JSONField(blank=True, default=list, verbose_name='最后一条 AI 选项'),
        ),
        migrations.AddField(
            model_name='outlineversion',
            name='last_question',
            field=models.TextField(blank=True, default='', verbose_name='最后一条 AI 问题'),
        ),
    ]
