# Generated by Django 4.2.30 on 2026-05-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlinechathistory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
