# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0002_add_is_deleted_to_chat_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineExpansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('world', '世界观'), ('magic', '设定体系'), ('history', '历史背景'), ('culture', '文化风俗'), ('location', '地点场景'), ('rule', '规则设定'), ('plot', '情节伏笔'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('key_name', models.CharField(max_length=200, verbose_name='关键词')),
                ('content', models.TextField(verbose_name='扩展内容')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('outline_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expansions', to='outline.outlineversion', verbose_name='大纲版本')),
            ],
            options={
                'verbose_name': '大纲扩展',
                'verbose_name_plural': '大纲扩展',
                'db_table': 'outline_expansion',
                'ordering': ['category', 'key_name'],
            },
        ),
    ]
