# Generated by Django 5.2.13 on 2026-09-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0004_delete_outlineexpansion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outline',
            options={'ordering': ['-version'], 'verbose_name': '大纲', 'verbose_name_plural': '大纲'},
        ),
        migrations.AlterModelTable(
            name='outline',
            table='outline',
        ),
    ]
