# Generated by Django 5.2.13 on 2026-09-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0005_alter_outline_options_alter_outline_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outline',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='outline',
            name='snapshot',
        ),
    ]
