# Generated by Django 5.2.13 on 2026-05-11 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='是否定稿')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否为当前版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_versions', to='volume.volumelist', verbose_name='卷')),
            ],
            options={
                'verbose_name': '章节版本',
                'verbose_name_plural': '章节版本',
                'db_table': 'chapter_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ChapterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(verbose_name='章节号')),
                ('title', models.CharField(max_length=255, verbose_name='章节标题')),
                ('summary', models.TextField(blank=True, verbose_name='章节摘要')),
                ('content', models.TextField(blank=True, verbose_name='章节内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='chapter.chapterversion', verbose_name='章节版本')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'db_table': 'chapter_list',
                'ordering': ['chapter_number'],
                'unique_together': {('chapter_version', 'chapter_number')},
            },
        ),
    ]
