# Generated by Django 5.2.13 on 2026-06-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterlist',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='是否锁定'),
        ),
    ]
