# Generated by Django 5.2.13 on 2026-06-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0002_chapterlist_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterlist',
            name='status',
            field=models.CharField(choices=[('summary', '已生成概述'), ('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
