# Generated by Django 5.2.13 on 2026-06-11 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0004_remove_chapterversion_link_volume'),
        ('volume', '0006_volumelist_chapter_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterlist',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='chapterlist',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='章节内容'),
        ),
        migrations.AlterField(
            model_name='chapterlist',
            name='status',
            field=models.CharField(choices=[('summary', '已生成概述'), ('draft', '草稿'), ('published', '已发布'), ('archived', '已归档'), ('failed', '生成失败'), ('deleted', '已删除')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='chapterlist',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='章节摘要'),
        ),
        migrations.AlterField(
            model_name='chapterlist',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='章节标题'),
        ),
        migrations.AlterField(
            model_name='chapterlist',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_list', to='volume.volumelist', verbose_name='卷'),
        ),
    ]
