# Generated by Django 5.2.13 on 2026-06-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0005_chapterlist_is_deleted_alter_chapterlist_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterlist',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='chapterlist',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='chapterlist',
            name='state',
            field=models.CharField(choices=[('normal', '正常'), ('locked', '已锁定'), ('deleted', '已删除')], default='normal', max_length=20, verbose_name='保护状态'),
        ),
        migrations.AlterField(
            model_name='chapterlist',
            name='status',
            field=models.CharField(choices=[('summary', '已生成概述'), ('draft', '草稿'), ('published', '已发布'), ('archived', '已归档'), ('failed', '生成失败')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
