from django.urls import path
from .views import (
    LoginView,
    LogoutView,
    RegisterView,
    ResetPasswordView,
    TokenUsageView,
    ApiTokenUsageToday,
    ApiTokenUsageStats,
    ProjectListView,
    ProjectCreateView,
    ProjectDetailView,
    ApiProjectDetailView,
    ApiProjectListView,
    ApiProjectCreateView,
    ApiProjectDeleteView,
    ApiProjectFinalizeView,
    ApiProjectUpdateView,
    ApiProjectStatsView,
    ApiOutlineVersionsView,
    ApiLatestOutlineView,
    ApiOutlineFinalizeView,
    ApiOutlineDeleteView,
    ApiUserView,
    ApiLoginView,
    ApiLogoutView,
    ApiRegisterView,
    ApiLLMConfigView,
    OutlineBuilderView,
    OutlineVersionDetailView,
    OutlineVersionContentApiView,
    VolumeBuilderView,
    VolumeVersionDetailView,
    ChapterSummaryView,
    ChapterVersionDetailView,
    ChapterGeneratorView,
    ChapterContentDetailView,
    ProjectUpdateTitleView,
    ProjectUpdateInfoView,
    ChapterContentApiView,
    LLMConfigView,
    VolumeGeneratorView,
    ContentManagerView,
    ApiVolumeGenerateView,
    ApiVolumeChatView,
    ApiVolumeVersionsView,
    ApiVolumeVersionView,
    ApiSaveVolumeVersionView,
    ApiVolumeFinalizeView,
    ApiVolumeDeleteView
)

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset_password'),
    path('token-usage/', TokenUsageView.as_view(), name='token_usage'),
    path('llm-config/', LLMConfigView.as_view(), name='llm_config'),
    path('volume_generator.html', VolumeGeneratorView.as_view(), name='volume_generator'),
    path('chapter_generator.html', ChapterGeneratorView.as_view(), name='chapter_generator'),
    path('content_manager.html', ContentManagerView.as_view(), name='content_manager'),
    path('', ProjectListView.as_view(), name='project_list'),
    path('create/', ProjectCreateView.as_view(), name='project_create'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('<int:pk>/outline/', OutlineBuilderView.as_view(), name='outline_builder'),
    path('<int:pk>/outline/version/<int:version_pk>/', OutlineVersionDetailView.as_view(), name='outline_version_detail'),
    path('<int:pk>/volume/', VolumeBuilderView.as_view(), name='volume_builder'),
    path('<int:pk>/volume/version/<int:version_pk>/', VolumeVersionDetailView.as_view(), name='volume_version_detail'),
    path('<int:pk>/volume/<int:volume_pk>/chapters/', ChapterSummaryView.as_view(), name='chapter_summary'),
    path('<int:pk>/volume/<int:volume_pk>/chapters/version/<int:version_pk>/', ChapterVersionDetailView.as_view(), name='chapter_version_detail'),
    path('<int:pk>/volume/<int:volume_pk>/chapters/generator/', ChapterSummaryView.as_view(), name='chapter_generator'),
    path('<int:pk>/volume/<int:volume_pk>/chapter/<int:chapter_pk>/', ChapterContentDetailView.as_view(), name='chapter_content_detail'),
    path('<int:pk>/update-title/', ProjectUpdateTitleView.as_view(), name='project_update_title'),
    path('<int:pk>/update-info/', ProjectUpdateInfoView.as_view(), name='project_update_info'),
    
    path('api/auth/user/', ApiUserView.as_view(), name='api_user'),
    path('api/auth/login/', ApiLoginView.as_view(), name='api_login'),
    path('api/auth/logout/', ApiLogoutView.as_view(), name='api_logout'),
    path('api/auth/register/', ApiRegisterView.as_view(), name='api_register'),
    
    path('api/projects/', ApiProjectListView.as_view(), name='api_project_list'),
    path('api/projects/<int:pk>/', ApiProjectDetailView.as_view(), name='api_project_detail'),
    path('api/projects/<int:pk>/stats/', ApiProjectStatsView.as_view(), name='api_project_stats'),
    path('api/projects/create/', ApiProjectCreateView.as_view(), name='api_project_create'),
    path('api/projects/<int:pk>/delete/', ApiProjectDeleteView.as_view(), name='api_project_delete'),
    path('api/projects/<int:pk>/update/', ApiProjectUpdateView.as_view(), name='api_project_update'),
    path('api/projects/<int:pk>/finalize/', ApiProjectFinalizeView.as_view(), name='api_project_finalize'),
    
    path('api/projects/<int:pk>/outline/versions/', ApiOutlineVersionsView.as_view(), name='api_outline_versions'),
    path('api/projects/<int:pk>/outline/latest/', ApiLatestOutlineView.as_view(), name='api_latest_outline'),
    
    path('api/token-usage/today/', ApiTokenUsageToday.as_view(), name='api_token_usage_today'),
    path('api/token-usage/stats/', ApiTokenUsageStats.as_view(), name='api_token_usage_stats'),
    
    path('api/chapter/<int:chapter_id>/content/', ChapterContentApiView.as_view(), name='chapter_content_api'),
    path('api/outline/version/<int:version_id>/', OutlineVersionContentApiView.as_view(), name='api_outline_version_content'),
    path('api/outline/finalize/', ApiOutlineFinalizeView.as_view(), name='api_outline_finalize'),
    path('api/outline/delete/', ApiOutlineDeleteView.as_view(), name='api_outline_delete'),
    
    path('api/llm-config/', ApiLLMConfigView.as_view(), name='api_llm_config'),
    
    path('api/volume/generate/', ApiVolumeGenerateView.as_view(), name='api_volume_generate'),
    path('api/volume/chat/', ApiVolumeChatView.as_view(), name='api_volume_chat'),
    path('api/projects/<int:project_id>/volume-versions/', ApiVolumeVersionsView.as_view(), name='api_volume_versions'),
    path('api/volume/version/<int:version_id>/', ApiVolumeVersionView.as_view(), name='api_volume_version'),
    path('api/volume/save/', ApiSaveVolumeVersionView.as_view(), name='api_volume_save'),
    path('api/volume/finalize/', ApiVolumeFinalizeView.as_view(), name='api_volume_finalize'),
    path('api/volume/delete/', ApiVolumeDeleteView.as_view(), name='api_volume_delete'),
]
