# Generated by Django 4.2.30 on 2026-05-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0008_alter_worldview_options_remove_worldview_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='事件标题')),
                ('description', models.TextField(blank=True, verbose_name='事件描述')),
                ('start_chapter', models.IntegerField(default=1, verbose_name='起始章节')),
                ('end_chapter', models.IntegerField(default=1, verbose_name='结束章节')),
                ('event_order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='project.projectlist', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '时间线事件',
                'verbose_name_plural': '时间线事件',
                'db_table': 'timeline_event',
                'ordering': ['event_order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_chat_histories', to='project.projectlist', verbose_name='项目')),
            ],
            options={
                'verbose_name': '时间线聊天历史',
                'verbose_name_plural': '时间线聊天历史',
                'db_table': 'timeline_chat_history',
                'ordering': ['created_at'],
            },
        ),
    ]
