# Generated by Django 4.2.30 on 2026-07-11 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='事件标题')),
                ('description', models.TextField(blank=True, verbose_name='事件描述')),
                ('era_unit', models.CharField(blank=True, default='', max_length=50, verbose_name='纪元单位')),
                ('start_year', models.IntegerField(default=0, verbose_name='开始年')),
                ('start_month', models.IntegerField(default=0, verbose_name='开始月')),
                ('end_year', models.IntegerField(default=0, verbose_name='结束年')),
                ('end_month', models.IntegerField(default=0, verbose_name='结束月')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='project.projectlist', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '时间线事件',
                'verbose_name_plural': '时间线事件',
                'db_table': 'timeline_event',
                'ordering': ['start_year', 'start_month', 'end_year', 'end_month'],
            },
        ),
    ]
