# Generated by Django 5.2.13 on 2026-09-10 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
        ('characters', '0003_character_source_charactertrajectory'),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='chapter.chapterlist', verbose_name='来源章节'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='timeline_events', to='characters.character', verbose_name='涉及人物'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('main', '主线'), ('side', '支线'), ('character', '人物'), ('world', '世界')], default='main', max_length=20, verbose_name='事件类型'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='is_time_estimated',
            field=models.BooleanField(default=False, verbose_name='时间是否为推断值'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='发生地点'),
        ),
    ]
