# Generated by Django 5.2.13 on 2026-05-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['time_order'], 'verbose_name': '时间线事件', 'verbose_name_plural': '时间线事件'},
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='end_chapter',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='event_order',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='start_chapter',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='end_time',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='start_time',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='起始时间'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='time_order',
            field=models.IntegerField(default=0, verbose_name='时间排序'),
        ),
    ]
