# Generated by Django 5.2.13 on 2026-06-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_alter_timelineevent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='end_month',
            field=models.IntegerField(default=0, verbose_name='结束月'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='end_year',
            field=models.IntegerField(default=0, verbose_name='结束年'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='era_unit',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='纪元单位'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='start_month',
            field=models.IntegerField(default=0, verbose_name='开始月'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='start_year',
            field=models.IntegerField(default=0, verbose_name='开始年'),
        ),
    ]
