# Generated by Django 5.2.13 on 2026-06-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_remove_timelineevent_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['start_year', 'start_month', 'end_year', 'end_month'], 'verbose_name': '时间线事件', 'verbose_name_plural': '时间线事件'},
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='time_order',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否使用'),
        ),
    ]
