# Generated by Django 5.2.13 on 2026-06-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_alter_timelineevent_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimelineChatHistory',
        ),
    ]
