# Generated by Django 5.2.13 on 2026-05-23 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0012_remove_worldviewchathistory_project_delete_worldview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.JSONField(blank=True, default=dict, help_text='{"identity":{"world_name":"","genre":""},"position":{"identity":"","tone":""},"summary":"","conflict":""}', verbose_name='基础设定')),
                ('foundation', models.JSONField(blank=True, default=dict, help_text='{"geography":{"continent_distribution":"","special_terrain":""},"calendar":{"era":"","days_per_year":"","seasons":"","festivals":""},"rules":{"natural_laws":"","boundaries":"","axioms":[]},"balance":""}', verbose_name='世界基础')),
                ('power', models.JSONField(blank=True, default=dict, help_text='{"energy":{"types":"","distribution":"","properties":""},"level":"","martial":{"categories":"","inheritance":""},"treasure":{"categories":"","pills":""},"beast":{"levels":"","mythical":""}}', verbose_name='力量体系')),
                ('races', models.JSONField(blank=True, default=dict, help_text='{"category":"","value":"","trait":{"lifespan":"","reproduction":"","physique":""},"relation":""}', verbose_name='种族族群')),
                ('society', models.JSONField(blank=True, default=dict, help_text='{"court":{"political_system":"","bureaucracy":""},"sect":{"levels":"","relationships":""},"martial":{"factions":"","alliances":""},"external":"","class":{"social_classes":"","mobility":""},"currency":{"types":"","rules":""},"resource":""}', verbose_name='社会结构')),
                ('culture', models.JSONField(blank=True, default=dict, help_text='{"custom":{"festivals":"","rituals":""},"language":{"languages":"","writing_system":""},"daily":{"clothing":"","cuisine":"","architecture":"","transportation":""},"religion":{"deities":"","organization":"","faith_differences":""}}', verbose_name='文化人文')),
                ('history', models.JSONField(blank=True, default=dict, help_text='{"ancient":"","modern":"","crisis":"","destiny":"","future":""}', verbose_name='历史进程')),
                ('special', models.JSONField(blank=True, default=dict, help_text='{"taboo":"","secret":"","fate":{"fortune_rules":"","destiny_types":""},"reincarnation":{"soul_rules":"","mechanics":""},"transmigration":"","system":"","rules":""}', verbose_name='特殊规则')),
                ('factions', models.JSONField(blank=True, default=list, verbose_name='阵营列表')),
                ('locations', models.JSONField(blank=True, default=list, verbose_name='地点列表')),
                ('relations', models.JSONField(blank=True, default=list, verbose_name='关系列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldviews', to='project.projectlist', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '世界观详细设定',
                'verbose_name_plural': '世界观详细设定',
                'db_table': 'worldview',
            },
        ),
        migrations.CreateModel(
            name='WorldViewChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('worldview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldview_chat_histories', to='worldview.worldview', verbose_name='所属世界观')),
            ],
            options={
                'verbose_name': '世界观聊天历史',
                'verbose_name_plural': '世界观聊天历史',
                'db_table': 'worldview_chat_history',
                'ordering': ['created_at'],
            },
        ),
    ]
