# Generated by Django 5.2.13 on 2026-05-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldview',
            name='factions',
        ),
        migrations.RemoveField(
            model_name='worldview',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='worldview',
            name='relations',
        ),
    ]
