# Generated by Django 5.2.13 on 2026-05-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldview', '0002_remove_worldview_factions_remove_worldview_locations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldview',
            name='overview',
        ),
        migrations.AddField(
            model_name='worldview',
            name='story_setting',
            field=models.JSONField(blank=True, default=dict, help_text='{"identity":{"world_name":"","genre":""},"position":{"identity":"","tone":""},"overview":"","conflict":""}', verbose_name='基础设定'),
        ),
    ]
