# Generated by Django 5.2.13 on 2026-05-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldview', '0003_remove_worldview_overview_worldview_story_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldview',
            old_name='story_setting',
            new_name='setting',
        ),
    ]
