# Generated by Django 5.2.13 on 2026-06-20 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_worldviewchathistory_project_delete_worldview_and_more'),
        ('worldview', '0004_rename_story_setting_worldview_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldview',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worldview', to='project.projectlist', verbose_name='所属项目'),
        ),
    ]
