# Generated by Django 5.2.13 on 2026-09-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldview', '0004_worldviewdocversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldviewdocchathistory',
            name='options',
            field=models.JSONField(blank=True, default=list, verbose_name='快捷选项'),
        ),
    ]
