# Generated by Django 5.2.13 on 2026-09-07 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldview', '0005_worldviewdocchathistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldviewdocchathistory',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_histories', to='worldview.worldviewdocversion', verbose_name='所属版本'),
        ),
        migrations.AddField(
            model_name='worldviewdocversion',
            name='last_options',
            field=models.JSONField(blank=True, default=list, verbose_name='最后一条 AI 选项'),
        ),
        migrations.AddField(
            model_name='worldviewdocversion',
            name='last_question',
            field=models.TextField(blank=True, default='', verbose_name='最后一条 AI 问题'),
        ),
    ]
