# Generated by Django 5.2.13 on 2026-09-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldview', '0007_worldview_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldview',
            name='genre',
        ),
    ]
